// mockData.ts
export const universities = [
  'Universitas Indonesia',
  'Institut Teknologi Bandung',
  'Universitas Gadjah Mada',
  'Institut Pertanian Bogor',
  'Universitas Airlangga',
  'Universitas Brawijaya',
  'Institut Teknologi Sepuluh Nopember',
  'Universitas Diponegoro',
  'Universitas Padjadjaran',
  'Universitas Negeri Jakarta',
  'Universitas Negeri Yogyakarta',
  'Universitas Negeri Malang',
  'Universitas Andalas',
  'Universitas Sumatera Utara',
  'Universitas Lampung'
];

export const majors = [
  'Teknik Informatika',
  'Sistem Informasi',
  'Teknik Komputer',
  'Ilmu Komputer',
  'Teknik Elektro',
  'Teknik Industri',
  'Teknik Mesin',
  'Teknik Sipil',
  'Arsitektur',
  'Manajemen',
  'Akuntansi',
  'Ekonomi',
  'Psikologi',
  'Hukum',
  'Ilmu Hukum',
  'Kedokteran',
  'Kedokteran Gigi',
  'Farmasi',
  'Matematika',
  'Statistika',
  'Fisika',
  'Kimia',
  'Biologi',
  'Ilmu Kelautan',
  'Teknik Pertambangan',
  'Teknik Geologi',
  'Desain Komunikasi Visual',
  'Desain Produk',
  'Sastra Inggris',
  'Sastra Indonesia'
];

export const locations = [
  'Jakarta',
  'Surabaya',
  'Bandung',
  'Medan',
  'Palembang',
  'Semarang',
  'Yogyakarta',
  'Malang',
  'Denpasar',
  'Makassar',
  'Banjarmasin',
  'Pontianak',
  'Balikpapan',
  'Manado',
  'Ambon',
  'Jayapura',
  'Kupang',
  'Mataram',
  'Banda Aceh',
  'Padang',
  'Bengkulu',
  'Jambi',
  'Gorontalo',
  'Palu',
  'Kendari',
  'Ternate',
  'Tanjung Pinang',
  'Pangkal Pinang'
];